FROM alpine:latest

# Install Chromium and necessary dependencies
RUN apk --no-cache add badwolf

CMD ["badwolf"]

# Specify the command to run when the container starts
#CMD ["chromium-browser", "--no-sandbox", "--disable-dev-shm-usage", "--disable-gpu"]

